FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Installation d'Angular CLI en global pour faciliter l'exécution
RUN npm install -g @angular/cli

EXPOSE 4200

# --host 0.0.0.0 est CRUCIAL pour que le container soit accessible depuis Windows/Mac
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]